spring:
  application:
    name: payment-service

  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/payment_service}
    username: ${PAYMENT_DB_USERNAME:payment}
    password: ${PAYMENT_DB_PASSWORD:payment_local}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
