-- 1:1 support chat between a customer and the shop admins. Each customer has one conversation.
-- Messages are never edited or deleted; they are the support record.
CREATE TABLE chat_rooms (
    id VARCHAR(36) PRIMARY KEY,
    -- Keycloak user id (access token subject). One room per customer.
    customer_id VARCHAR(64) NOT NULL UNIQUE,
    customer_email VARCHAR(255),
    customer_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Newest message, for the admin room list. A room is created together with its first message.
    last_message_id BIGINT,
    last_message_at TIMESTAMP WITH TIME ZONE,
    last_sender_type VARCHAR(16) CHECK (last_sender_type IN ('CUSTOMER', 'ADMIN')),
    -- Newest message id each side has read. Unread messages are the other side's messages after it.
    customer_read_message_id BIGINT NOT NULL DEFAULT 0 CHECK (customer_read_message_id >= 0),
    admin_read_message_id BIGINT NOT NULL DEFAULT 0 CHECK (admin_read_message_id >= 0),
    CHECK ((last_message_id IS NULL) = (last_message_at IS NULL)
        AND (last_message_id IS NULL) = (last_sender_type IS NULL))
);

CREATE INDEX chat_rooms_last_message_idx ON chat_rooms (last_message_id DESC);

CREATE TABLE chat_messages (
    -- Messages of a room are inserted while holding the room row lock,
    -- so ids within a room follow commit order and reading "after id N" never skips one.
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room_id VARCHAR(36) NOT NULL REFERENCES chat_rooms(id),
    sender_type VARCHAR(16) NOT NULL CHECK (sender_type IN ('CUSTOMER', 'ADMIN')),
    sender_id VARCHAR(64) NOT NULL,
    -- Generated by the browser. A resent message with the same id is stored once.
    client_message_id VARCHAR(36) NOT NULL,
    content VARCHAR(1000) NOT NULL CHECK (length(btrim(content)) > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (room_id, client_message_id)
);

CREATE INDEX chat_messages_room_idx ON chat_messages (room_id, id);
